sudo: required
dist: trusty

language: node_js
node_js: 8

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=latest
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download
  
  
script:
  - lix run travix interp
  - lix run travix neko
  - lix run travix python
  - lix run travix node
  - lix run travix node -D tink_json_compact_code
  - lix run travix lua
  - lix run travix lua -D tink_json_compact_code
  # - lix run travix flash
  - lix run travix java
  - lix run travix cs -D erase-generics
  # - lix run travix cs
  - lix run travix cpp
  - lix run travix php

jobs:
  include:
    # - stage: test # should uncomment this when there is no matrix above (e.g. only one os, one env, etc)
    - stage: deploy
      language: haxe
      haxe: "3.4.7"
      os: linux
      install: skip
      script: skip
      env:
        - secure: "XDghC3Ee8+78aCuTbyVOEGxmuG2siqdhGZGTmiEYyCnoUUXeLu9w5HKGSXqN4wfnhPbjg3vMqcDC8/rA1caNj0xVerJAOZHTttgzGgmtxhVtfal2flv4vNLjAm6TtDM8+rmJ/N+3/6iN0X9KJNBaDi8ZPo1e//Pa/Kk7V/aygEE0keCrmS28mmOTkz7XpUx5qGLiutn9JRMq1lOKsgGtU3oc4OvJuD6l9E4bdC1frmPrSi7Ou6VKvkCXbKC0eF3eAusIaE/9xxtOxXBHlJVbMqGjvGoY6OmAiM7JPMvC5Z8AMnZllwpLCqN8tS97rHqKkS5WLwom6Jb9Qkr2AxDlzyd+Bs6SZwMsLW7rPO5vIjzKe8oIy2VKEU59TrjoQx62ScugfMKXok/AFGvB9lt0sIsTTQy2HoBq67hYuUO61DIrBvhq6t0t2wm+PacI1dBBwCs+KUyuiu6dKKFo6jDBye9RM6ZqaM0FYBxcdqODOm75Xany3t6H3dUqEFIDE3WJq/pP6gaWMarHpj/Qkrxr73Km1TyEHZ8fcgr452lKTdXK/R4mz15NCD/aIZJ+J8kDobFbrw/IH2nFcKpjt4ihq7t2WtMg9aCv5K4KNVE9G1hQ/+XDbqviyxPA6U9OW2ae4fTmFYG2UjqvJnsu0+WZ46CS4zFQbtuUHptzjF0NZhI="
      after_success:
        - haxelib install travix
        - haxelib run travix install
        - haxelib run travix release